---
- name: "Add device with IP from range"
  connection: local
  hosts: localhost
  strategy: free
  gather_facts: False
  vars:
    ansible_async_dir: /dev/shm

  tasks:
    - name: add device
      netbox.netbox.netbox_device:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: "{{ validate_certs }}"
        data:
            name: "{{ device_name }}"
            site: "{{ site }}"
            device_type: "{{ device_type }}"
            serial: "{{ device_serial }}"
            device_role: "{{ device_role }}"
            comments: "{{ comments }}"
            status: "{{ status }}"

    - name: Get a new available IP inside <<range>>
      netbox.netbox.netbox_ip_address:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: "{{ validate_certs }}"
        data:
          prefix: "{{ ip_range }}"
          assigned_object:
            name: Default Interface
            device: "{{ device_name }}"
        state: new
      register: add_ip_address

    - name: set primary
      netbox.netbox.netbox_device:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: "{{ validate_certs }}"
        data:
          name: "{{ device_name }}"
          primary_ip4:
            address: "{{ add_ip_address.ip_address.address }}"
