---
- name: "Add devices"
  hosts: localhost
  connection: local
  strategy: free
  gather_facts: False
  vars:
    ansible_async_dir: /dev/shm
    netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
    netbox_url: "{{ lookup('env', 'NETBOX_URL') }}"
    default_interface: "Default Interface"

  tasks:
    - name: add device
      netbox.netbox.netbox_device:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
            name: "{{ dev['name'] }}"
            site: "{{ dev['site'] }}"
            device_type: "{{ dev['device_type'] }}"
            serial: "{{ dev['serial'] }}"
            device_role: "{{ dev['device_role'] }}"
            comments: "{{ dev['comments'] }}"
            status: "{{ dev['status'] }}"
            custom_fields:
              origin: "{{ dev['cf_origin'] | default(omit,true) }}"
              bbsites_id: "{{ dev['cf_bbsites_id'] | default(omit,true) }}"
      loop_control:
        label: "{{ dev['name'] }}"
        loop_var: "dev"
      with_items: "{{ devices }}"

    - name: add_interface
      netbox.netbox.netbox_device_interface:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          device: "{{ dev['name'] }}"
          name: "{{ dev['interface'] | default(default_interface) }}"
          # this complicates the "add device" thing
          type: Virtual
      loop_control:
        label: "{{ dev['name'] }}"
        loop_var: "dev"
      with_items: "{{ devices }}"

    - name: add_ip_address
      netbox.netbox.netbox_ip_address:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          prefix: "{{ dev['ip4'] }}"
          assigned_object:
            name: "{{ dev['interface'] | default(default_interface) }}"
            device: "{{ dev['name'] }}"
      loop_control:
        label: "{{ dev['name'] }}"
        loop_var: "dev"
      with_items: "{{ devices }}"
      when: dev['ip4'] != None
      tags:
        - add_ip_address

    - name: add_mac_address
      netbox.netbox.netbox_device_interface:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          device: "{{ dev['name'] }}"
          name: "{{ dev['interface'] | default(default_interface) }}"
          mac_address: "{{ dev['mac'] }}"
      loop_control:
        label: "{{ dev['name'] }}"
        loop_var: "dev"
      with_items: "{{ devices }}"
      when: dev['mac'] != None

    - name: set primary
      netbox.netbox.netbox_device:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          name: "{{ dev['name'] }}"
          primary_ip4:
            address: "{{ dev['ip4'] }}"
      loop_control:
        label: "{{ dev['name'] }}"
        loop_var: "dev"
      with_items: "{{ devices }}"

    - name: add ip6
      netbox.netbox.netbox_ip_address:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          address: "{{ dev['ip6'] }}"
          assigned_object:
            name: "{{ dev['interface'] | default(default_interface) }}"
            device: "{{ dev['name'] }}"
      loop_control:
        label: "{{ dev['name'] }}"
        loop_var: "dev"
      with_items: "{{ devices }}"
      when: dev['ip6'] != None
      ignore_errors: True

    - name: set primary_ip6
      netbox.netbox.netbox_device:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          name: "{{ dev['name'] }}"
          primary_ip6:
            address: "{{ dev['ip6'] }}"
      loop_control:
        label: "{{ dev['name'] }}"
        loop_var: "dev"
      with_items: "{{ devices }}"
      when: dev['ip6'] != None
      ignore_errors: True
